variables:
  GIT_DEPTH: 2

default:
  interruptible: true
  timeout: 5m

stages:
  - lint
  - test

lint:app:
  stage: lint
  image:
    name: koalaman/shellcheck-alpine:v0.10.0
    entrypoint: [""]
  script:
    - |
      for file in $(find -name "*.sh" -type f); do
        shellcheck --format=gcc --severity=error $file
      done

lint:config:
  stage: lint
  image: registry.gitlab.com/pipeline-components/yamllint:latest
  script:
    - yamllint .

test:
  stage: test
  image: bash:5.2.37-alpine3.21
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apk add jq yq zsh
  script:
    - ./test/bats/bin/bats test/smoke.bats
